[package]
name = "rust_console1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.48", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
